#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal blog about sports and analytics '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-112742997-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'https-samirak93-github-io-analytics'

#-------------------------------
# About Section

about: >
  # Samira Kumar Bio
  
  Hi. I’m Samira Kumar from India. I currently live in Irvine, California, pursuing my <b>Masters in Business Analytics</b> at <b>UC Irvine</b> for 2018-19. I’m interested in the statistical and technological side of sports(especially football/soccer) and will use this blog to publish new ideas and concepts. I’m always looking to improve and learn new concepts.
  <br><br>
  I’m currently working with Python and Tableau and started learning R as well. I also use Coral Video Studio and Coral Draw for video and image editing.
  Please feel free to contact me. You can find my contact details on the [contacts](https://samirak93.github.io/analytics/pages/contact.html) page
  
contact: >
  # 
  You can find my LinkedIN page here: [LinkedIN](https://www.linkedin.com/in/samirakumar/)
  You may contact me [through my email](mailto:samirakumar@yahoo.com) or [tweet to me](https://twitter.com/intent/tweet?text=%40Samirak93) if you have any questions or would like to bring up any issues.
#-------------------------------

# Work Section

projects:
- {name: 'Where do teams cross?', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Dynamic Pass Network Map', folder: 'proj-2', file: 'projects/proj-2.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/Samirak93'}
- {icon: 'github', link: 'https://github.com/samirak93'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/samirakumar/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
